### ISSUE TITLE
Improve layout on launch

### ISSUE THREAD

**Issue by dullin** [privat/rars#27]
Unsure if this is macOS specific.

When opening RARS, the window layout is not conductive to understanding the program.

The edit pane is completely minimized. It should take most of the window real-estate.

Should we have a new file automaticly opened for ease of use? If we then open a file with an empty new file, it is discarded?

![CleanShot 2024-07-01 at 09 44 30@2x](https://github.com/privat/rars/assets/7041033/0e0e7484-a775-40e7-9279-3af0c7c2445d)

**Comment by privat** [comment]
> The edit pane is completely minimized. It should take most of the window real-estate.

I do not experience that. Could it be a OSX issue ? Or a high resolution issue ?

**Comment by privat** [comment]
> Should we have a new file automaticly opened for ease of use? If we then open a file with an empty new file, it is discarded?

Good idea
