### ISSUE TITLE
Investigate jpackage

### ISSUE THREAD

**Issue by privat** [privat/rars#60]
Having autonomous and fully packaged RARS could be helpful, so we should investigate jpackage and the related maven plugins.

**Comment by ElTitoDG** [comment]
Searching plugins I have found this one [petr-panteleyev jpackage-maven-plugin](https://github.com/petr-panteleyev/jpackage-maven-plugin?tab=readme-ov-file) which seems to have more support than this one [akman jpackage-maven-plugin](https://github.com/akman/jpackage-maven-plugin)

**Comment by ElTitoDG** [comment]
Pull request #62
